# FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-buster-slim-arm32v7 AS base
WORKDIR /app
 
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["Deconz2Mqtt.csproj", "./"]
RUN dotnet restore "./Deconz2Mqtt.csproj" -r linux-arm
COPY . .
WORKDIR "/src/."
RUN dotnet build "Deconz2Mqtt.csproj" -c Release -o /app/build  -r linux-arm
 
FROM build AS publish
RUN dotnet publish "Deconz2Mqtt.csproj" -c Release -o /app/publish -r linux-arm --self-contained false --no-restore
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Deconz2Mqtt.dll"]