FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
 
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["Deconz2Mqtt.csproj", "./"]
RUN dotnet restore "./Deconz2Mqtt.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Deconz2Mqtt.csproj" -c Release -o /app/build
 
FROM build AS publish
RUN dotnet publish "Deconz2Mqtt.csproj" -c Release -o /app/publish --self-contained false --no-restore
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Deconz2Mqtt.dll"]